### ISSUE TITLE
Use speck.getCurrentSample() instead of speck.getSample()

### ISSUE THREAD

**Issue by chrisbartley** [jywarren/opk-speck-cli#4]
I saw your note in the README about periodically sampling instead of averaging.  If I understand the motivation, it's that you want to periodically get the current sample value and write that to a file or whatever.  If so, you'd be better off calling speck.getCurrentSample() instead of speck.getSample().  The latter will return a historical sample--one that was recorded in the past and saved to the Speck's internal memory (or null if you've read everything and there's no saved data).  If you call that, then there's no reason not to call it as fast as possible (until you get a null, and then there's no reason to call it more often than the Speck's logging interval).

If, however, you really only want the current value and don't care about history, you should definitely be using speck.getCurrentSample().  But then you have to do the averaging yourself.

That said, you can get the averaging for free if you set the speck's sample interval (speck. setLoggingInterval()) and then read historical data with speck.getSample().  So, for example, if you want samples at 5 second intervals, then set the logging interval to 5.  The speck will aggregate samples during those 5 seconds and save the average value to memory.  Since the logging interval is stored as a byte, you're limited to a max logging interval of 255, but that should be sufficient for most use cases.

**Comment by jywarren** [comment]
Oh, thanks! If we set the interval, how do we know for which time period the last historical sample corresponds to? If there are more than one (say, if we haven't asked for a while) will there be multiple with timestamps pegged to the end of the sample period? Does each historical sample indicate start/end times or the interval it was measured over?

I guess to keep things simple, we're probably going to average in the driver (getCurrentSample) as a set-able parameter, which will simplify this, and it's pretty easy; we do the same on several other sensors.

**Comment by chrisbartley** [comment]
Historical samples look exactly like current samples--that is, they both have the same fields in the object. So, no, there's no way to know simply by looking at a single historical sample what the logging interval was when the sample was recorded.  For historical samples, you could look at the timestamp of the previous sample and get the logging interval by compute the difference, at least to make a guess (if you assume that the Speck was not turned off between samples).  For current samples, the interval between samples will always be 1 second.

If you're going to do the averaging yourself, you'll get the best data if you call getCurrentSample() at 1Hz (or faster) and then average over whatever duration you want.  If you'd rather the Speck do the averaging, then set the logging interval to your desired duration, and then use getSample().
